#!/bin/bash

# start docker and emacs
#docker run -d \
#    --volume $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
#    -p 5000:5000 \
#    --memory="500m" \
#    --memory-swap="1g" \
#    --env DISPLAY=${DISPLAY} \
#    --net="host" \
docker run  --rm -ti \
    --volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
    --volume ${PWD}/project:/project \
    --volume $XAUTHORITY:/developer/.Xauthority \
    -e DISPLAY \
    --env XAUTHORITY=/developer/.Xauthority \
    --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
    --user $(id -u ${USER}):$(id -g ${USER}) \
    --volume "${HOME}/.conan:/home/developer/.conan" \
    --volume "${HOME}/.ssh:/home/developer/.ssh" \
    --volume ${PWD}/dotfiles/.vim:/home/developer/.vim \
    --volume ${HOME}/.m2:/home/developer/.m2 \
    --volume ${PWD}/dotfiles/.vimrc:/home/developer/.vimrc \
    --volume ${PWD}/dotfiles/.bashrc:/home/developer/.bashrc  \
    --volume "$PWD:/home/developer/workspace" \
    --device /dev/snd \
    --name docker-vscode \
    --privileged doevelopper/editors:0.0.1

#      --entrypoint "urxvt" \
# alternatively, you can map your settings into the container
# docker run -it \
#        -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
#        -v $XAUTHORITY:/developer/.Xauthority \
#        -v ${HOME}/.config/Code:/developer/.config/Code \
#        -v ${HOME}/.vscode:/developer/.vscode \
#        -v ${HOME}/.ssh:/developer/.ssh \
#        -v ${HOME}/.gitconfig:/developer/.gitconfig \
#        -v ${PWD}/project:/project \
#        -v ${SSH_AUTH_SOCK}:/ssh_auth_sock \
#        -e SSH_AUTH_SOCK=/ssh_auth_sock \
#        -e DISPLAY=unix${DISPLAY} \
#        -e XAUTHORITY=/developer/.Xauthority \
#        -p 5000:5000 \
#        --device /dev/snd \
#        --name docker-vscode \
#        --entrypoint "xterm" \
#        registry.gear.ge.com/100034251/ide:latest

#docker exec docker-vscode /developer/bin/start-vscode
#docker exec docker-vscode /developer/bin/start-emacs


