#         cfs-com/.gitlab/ci/base.yml
#
#               Copyright (c) 2014-2018 A.H.L
#
#        Permission is hereby granted, free of charge, to any person obtaining
#        a copy of this software and associated documentation files (the
#        "Software"), to deal in the Software without restriction, including
#        without limitation the rights to use, copy, modify, merge, publish,
#        distribute, sublicense, and/or sell copies of the Software, and to
#        permit persons to whom the Software is furnished to do so, subject to
#        the following conditions:
#
#        The above copyright notice and this permission notice shall be
#        included in all copies or substantial portions of the Software.
#
#        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#        EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#        NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#        LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#        OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#        WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

docker:build:dds-base:
    stage: Build base image
    extends:
        - .create-docker-container
    variables:
        GOAL: build
        PLATFORM: ""
        BUMP_VERSION: "0.0.2"
        MODULE: "common-base"
        MODULE_DIR: common
        DOCKER_FILE: src/main/resources/docker/${ARCH}/${MODULE_DIR}/Dockerfile
    # only:
        # changes: [ subdir/**/*, Dockerfile, requirement.txt

docker:build:rti-dds-base:
    stage: Build base image
    extends:
        - .create-docker-container
    variables:
        GOAL: build
        PLATFORM: "RTI"
        BUMP_VERSION: "5.3.3"
        MODULE: "rti-connext-dds"
        MODULE_DIR: rti
        DOCKER_FILE: src/main/resources/docker/${ARCH}/${MODULE_DIR}/Dockerfile
    # only:
    #    variables:
    #        - $BASE == "yes"

